# Generated by Django 2.2.8 on 2020-01-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxicsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=255)),
                ('series_link', models.CharField(max_length=255)),
            ],
        ),
    ]
