# Generated by Django 2.2.8 on 2020-01-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxicsearch', '0002_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='series',
            name='series_link',
            field=models.URLField(),
        ),
    ]
